### ISSUE TITLE
Old virtualenv breaks REST service installation

### ISSUE THREAD

**Issue by tsznuk** [cloudify-cosmo/cloudify-manager#948]
When trying to bootstrap the manager on a CentOS 7 box on which the python-virtualenv package has been installed the following error is generated:

```
Workflow failed: Task failed 'fabric_plugin.tasks.run_script' -> restservice 
 error: http: //127.0.0.1:8100: <urlopen error [Errno 111] Connection refused>
```

This happens because the virtualenv available in CentOS is too old. It contains a buggy version of pip (1.4.1). That version gets installed in ` /opt/manager/env/` and is then used to install the REST service. But due to a bug (pypa/pip#1067) the gunicorn startup script is not placed in `/opt/manager/env/bin/`.

The REST service install script is capable of installing virtualenv if it is missing, but does not attempt to upgrade if the current version is too old. Adding the `--upgrade` flag to the install command should fix this.

**Comment by tehasdf** [comment]
Fixed in #949
